{% set name = "odc-apps-dc-tools" %}
{% set version = "1.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9fe581f13eb61206d0f8b3d364da138b175fd7245d3f7c995fb71f9213dbdda4

build:
  entry_points:
    - azure-to-dc = odc.apps.dc_tools.azure_to_dc:cli
    - azure-to-tar = odc.apps.dc_tools.azure_to_tar:cli
    - cop-dem-to-dc = odc.apps.dc_tools.cop_dem_to_dc:cli
    - dc-sync-products = odc.apps.dc_tools.add_update_products:cli
    - dc-index-from-tar = odc.apps.dc_tools.index_from_tar:cli
    - dc-index-export-md = odc.apps.dc_tools.export_md:cli
    - esa-wc-to-dc = odc.apps.dc_tools.esa_worldcover_to_dc:cli
    - fs-to-dc = odc.apps.dc_tools.fs_to_dc:cli
    - gs-to-tar = odc.apps.dc_tools.gs_to_tar:cli
    - redrive-queue = odc.apps.dc_tools.redrive_to_queue:cli
    - s3-find = odc.apps.dc_tools.s3_find:cli
    - s3-inventory-dump = odc.apps.dc_tools.s3_inventory:cli
    - s3-to-dc = odc.apps.dc_tools.s3_to_dc:cli
    - s3-to-tar = odc.apps.dc_tools.s3_to_tar:cli
    - sqs-to-dc = odc.apps.dc_tools.sqs_to_dc:cli
    - stac-to-dc = odc.apps.dc_tools.stac_api_to_dc:cli
    - thredds-to-dc = odc.apps.dc_tools.thredds_to_dc:cli
    - thredds-to-tar = odc.apps.dc_tools.thredds_to_tar:cli

  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - aiobotocore
    - click <8.3
    - fsspec
    - pystac-client >=0.2.0
    - pyyaml
    - datacube >=1.9.12,<1.10.0
    - odc-cloud
    - odc-geo
    - odc-io
    - pystac >=1.0.0,<2
    - rio-stac
    - datadog
    - toolz

test:
  imports:
    - odc
  commands:
    - pip check
    - dc-sync-products --help
    - dc-index-from-tar --help
    - dc-index-export-md --help
    - s3-to-dc --help
    - sqs-to-dc --help
    - stac-to-dc --help
    - fs-to-dc --help
    - cop-dem-to-dc --help
    - esa-wc-to-dc --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opendatacube/odc-tools/
  summary: CLI utils for working with a datacube index
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pjonsson
    - Ariana-B
    - omad
    - SpacemanPaul
