{% set name = "odc-apps-dc-tools" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4037e6fde5a5282342a5a7bf0adbcb84ad404c73f9b56e5a8e44a0d4b42d476d

build:
  entry_points:
    - dc-sync-products = odc.apps.dc_tools.add_update_products:cli
    - dc-index-from-tar = odc.apps.dc_tools.index_from_tar:cli
    - dc-index-export-md = odc.apps.dc_tools.export_md:cli
    - s3-to-dc = odc.apps.dc_tools.s3_to_dc:cli
    - sqs-to-dc = odc.apps.dc_tools.sqs_to_dc:cli
    - stac-to-dc = odc.apps.dc_tools.stac_api_to_dc:cli
    - fs-to-dc = odc.apps.dc_tools.fs_to_dc:cli
    - cop-dem-to-dc = odc.apps.dc_tools.cop_dem_to_dc:cli
    - esa-wc-to-dc = odc.apps.dc_tools.esa_worldcover_to_dc:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - aiobotocore
    - click
    - fsspec
    - pystac-client >=0.2.0
    - toolz
    - pyyaml
    - datacube >=1.9.0
    - odc-io
    - odc-cloud
    - pystac >=1.0.0
    - rio-stac
    - urlpath
    - datadog
    - eodatasets3 >=1.9.0
    - odc-stac

test:
  imports:
    - odc
  commands:
    - pip check
    - dc-sync-products --help
    - dc-index-from-tar --help
    - dc-index-export-md --help
    - s3-to-dc --help
    - sqs-to-dc --help
    - stac-to-dc --help
    - fs-to-dc --help
    - cop-dem-to-dc --help
    - esa-wc-to-dc --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opendatacube/odc-tools/
  summary: CLI utils for working with a datacube index
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Ariana-B
    - omad
    - SpacemanPaul
